"""Permutation-null + BH-FDR for the scoring engine.

Q3.2 acceptance: per-module FDR per (species, cell_state) using
size-matched random gene sets drawn from ``adata.var_names``.

Design choices:

- Aggregation unit = (species, cell_state). That is the unit of test
  Q3.3 needs (conserved vs divergent classification). A per-cell FDR
  would be ~25 000 tests per module and is not what the next phase
  consumes.
- Null draws are size-matched random subsets of ``adata.var_names``
  (with replacement across permutations but not within a single
  draw). The full backbone is fair — using the genes the dataset
  actually carries keeps the null on the same expression-prevalence
  distribution as the real set.
- p-value is one-sided, ``rho == fraction(null_means >= observed_mean)``;
  Lancaster-style ``+1/N+1`` pseudocount to avoid p = 0.
- BH-corrects across the full module × group grid in one shot.

The shuffled scores reuse ``scanpy.tl.score_genes`` so the null is
generated by exactly the same algorithm as the observed score
(including the internal control-gene sampling); only the input gene
list changes.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc

from src.scoring.engine import _map_genes

logger = logging.getLogger(__name__)

_RNG_DEFAULT_SEED = 0


@dataclass(frozen=True)
class NullConfig:
    n_permutations: int = 200
    seed: int = _RNG_DEFAULT_SEED
    group_key: str = "cell_state"
    species_key: str = "species"


def score_with_null(
    adata: ad.AnnData,
    gene_sets: dict[str, list[str]],
    species_to_backbone: dict[str, str | None],
    config: NullConfig | None = None,
) -> pd.DataFrame:
    """Run permutation-null FDR per (species, group) × module.

    Parameters
    ----------
    adata
        Already-scored AnnData with one ``.obs`` column per module name in
        ``gene_sets`` (call ``score_all_modules`` first). Must have
        ``species_key`` and ``group_key`` columns.
    gene_sets
        Mapping ``module_name → human gene symbols``. Mapped per-species
        via the same ``_map_genes`` path used by the observed score.
    species_to_backbone
        Mapping ``species → ortholog backbone path or None``. ``None`` for
        human (identity mapping).
    config
        See :class:`NullConfig`.

    Returns
    -------
    pandas.DataFrame
        Long table indexed by ``(module, species, group)`` with columns
        ``observed_mean, null_mean, null_std, n_cells, pval, fdr``.
        ``fdr`` is Benjamini-Hochberg across the entire returned table.
    """
    cfg = config or NullConfig()
    if cfg.species_key not in adata.obs.columns:
        msg = f"adata.obs['{cfg.species_key}'] missing"
        raise ValueError(msg)
    if cfg.group_key not in adata.obs.columns:
        msg = f"adata.obs['{cfg.group_key}'] missing"
        raise ValueError(msg)
    for m in gene_sets:
        if m not in adata.obs.columns:
            msg = f"adata.obs['{m}'] missing — call score_all_modules() first"
            raise ValueError(msg)

    rng = np.random.default_rng(cfg.seed)
    rows: list[dict[str, object]] = []

    species_levels = sorted(map(str, adata.obs[cfg.species_key].unique()))
    for module, genes in gene_sets.items():
        for sp in species_levels:
            sp_mask = (adata.obs[cfg.species_key] == sp).values
            if sp_mask.sum() < 5:
                continue
            sub = adata[sp_mask].copy()
            mapped = _map_genes(
                genes,
                species=sp,
                backbone_path=species_to_backbone.get(sp),
                var_names=sub.var_names,
                set_name=module,
            )
            if len(mapped) < 2:
                logger.warning(
                    "Skip null for %s in %s: only %d genes after mapping",
                    module,
                    sp,
                    len(mapped),
                )
                continue
            null_cell_scores = _null_score_matrix(sub, len(mapped), cfg.n_permutations, rng)

            groups = sub.obs[cfg.group_key].astype(str).values
            observed = sub.obs[module].astype(float).values
            for grp in pd.unique(groups):
                mask = groups == grp
                if mask.sum() < 3:
                    continue
                obs_mean = float(observed[mask].mean())
                null_means = null_cell_scores[mask, :].mean(axis=0)
                # one-sided: are observed module scores higher than random?
                # use absolute deviation so depleted modules also score.
                obs_dev = abs(obs_mean - null_means.mean())
                null_dev = np.abs(null_means - null_means.mean())
                hits = int((null_dev >= obs_dev).sum())
                pval = (hits + 1) / (cfg.n_permutations + 1)
                rows.append(
                    {
                        "module": module,
                        "species": sp,
                        "group": grp,
                        "observed_mean": obs_mean,
                        "null_mean": float(null_means.mean()),
                        "null_std": float(null_means.std(ddof=1)),
                        "n_cells": int(mask.sum()),
                        "pval": float(pval),
                    }
                )

    if not rows:
        return pd.DataFrame(
            columns=[
                "module",
                "species",
                "group",
                "observed_mean",
                "null_mean",
                "null_std",
                "n_cells",
                "pval",
                "fdr",
            ]
        )

    out = pd.DataFrame(rows)
    out["fdr"] = _bh(out["pval"].values)
    return out.sort_values(["module", "species", "group"]).reset_index(drop=True)


def _null_score_matrix(
    adata: ad.AnnData,
    set_size: int,
    n_permutations: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Compute (n_cells × n_permutations) null score matrix.

    Each column is a ``scanpy.tl.score_genes`` call against a random
    size-``set_size`` subset of ``adata.var_names``. Uses ``score_genes``
    rather than a hand-rolled mean so the null and observed share the
    same control-gene-binning behaviour.
    """
    var_names = np.asarray(adata.var_names)
    matrix = np.empty((adata.n_obs, n_permutations), dtype=np.float32)
    for j in range(n_permutations):
        idx = rng.choice(var_names.size, size=set_size, replace=False)
        gene_list = var_names[idx].tolist()
        sc.tl.score_genes(
            adata,
            gene_list=gene_list,
            score_name="_null_tmp",
            use_raw=False,
            random_state=int(rng.integers(0, 2**31 - 1)),
        )
        matrix[:, j] = adata.obs["_null_tmp"].astype(np.float32).values
    if "_null_tmp" in adata.obs.columns:
        del adata.obs["_null_tmp"]
    return matrix


def _bh(pvals: np.ndarray) -> np.ndarray:
    """Benjamini-Hochberg FDR (independent / positive-dep)."""
    p = np.asarray(pvals, dtype=float)
    n = p.size
    order = np.argsort(p)
    ranked = p[order]
    adj = ranked * n / (np.arange(n) + 1)
    # enforce monotone non-decreasing from the largest rank downward
    adj = np.minimum.accumulate(adj[::-1])[::-1]
    out = np.empty(n, dtype=float)
    out[order] = np.clip(adj, 0.0, 1.0)
    return out
